# Generated by Django 5.2.8 on 2025-12-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
