# Generated by Django 5.2.8 on 2025-12-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_product_on_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
